#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "NeoSolarized"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = "myfunction#before"
    automatic_update = 1
    lint_on_the_fly = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

#[[layers]]
#name = 'shell'
#default_position = 'top'
#default_height = 30

[[layers]]
name = 'colorscheme'

[[layers]]
name = "lang#c"
[[layers]]
name = "lang#java"
[[layers]]
name = "lang#javascript"
[[layers]]
name = "lang#vim"
[[layers]]
name = "lang#python"
format-on-save = 1
[[layers]]
name = "git"
[[layers]]
name = "github"
[[layers]]
name = "VersionControl"
[[layers]]
name = "tools"
[[layers]]
name = "checkers"
[[layers]]
name = "denite"
[[layers]]
name = "lang#dockerfile"
[[layers]]
name = "lang#html"
#[[layers]]
#name = "tmux"

[[custom_plugins]]
name = "vimwiki/vimwiki"
merged = false

[[custom_plugins]]
name ="wakatime/vim-wakatime"
merged = false



